import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux/ReduxProvider";
import { UserProvider } from "@/store/context/UserContext";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ReduxProvider>
          <UserProvider>
          {children}
          </UserProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
